### ISSUE TITLE
Scrolling overlay background

### ISSUE THREAD

**Issue by PeteJodo** [1stdibs/react-modal-wrapper#5]
When a modal is open, it's still possible to scroll the page behind the modal, behind the overlay. 

1. fix this by having the component change the style of the `html`/`body` tag (yuck!) to `height: 100%; overflow: auto;` (overflow: hidden will cause a jump to the top of the page I believe)

2. Another option that would keep it from scrolling and contained within the functionality of the component is by having an event listener listening for scroll events and if the element the event occurred over isn't the modal then just do a simple `e.preventDefault()`

**Comment by PeteJodo** [comment]
+@robrichard what do you think about solution 2?

**Comment by robrichard** [comment]
How would #2 work if you also have a modal that is larger than the viewport?

**Comment by PeteJodo** [comment]
The modal can't be larger than the viewport. It can only be as large as the viewport at which point, if the content of the modal is larger than the viewport, it becomes scrollable (only in the y-direction though).

I would do solution 2 in a very similar way I did `closeOnOutsideClick` [here](https://github.com/1stdibs/react-modal-wrapper/blob/master/lib/FlexModalWrapper.js#L13-L29). Attach event listeners when component mounts and detach them when the component unmounts and then the listener would just look like...
```javascript
handleScrollOutside(e) {
  if (isNodeInRoot(e.target, findDOMNode(this.refs.content))) {
    return;
  }
  e.preventDefault();
}
```

**Comment by PeteJodo** [comment]
So this works (but not for touch-based scrolling)...
```javascript
handleScrollOutside(e) {
  const contentNode = findDOMNode(this.refs.content).childNodes[0].childNodes[0];
  const { scrollTop, scrollHeight, offsetHeight } = contentNode;
  const delta = e.wheelDelta;
  const up = delta > 0;
  const prevent = () => {
    e.stopPropagation();
    e.preventDefault();
    e.returnValue = false;
  }

  if (!isNodeInRoot(e.target, contentNode)) {
    return prevent();
  }

  if (!up && -delta > scrollHeight - offsetHeight - scrollTop) {
    contentNode.scrollTop = scrollHeight;
    return prevent();
  } else if (up && delta > scrollTop) {
    contentNode.scrollTop = 0;
    return prevent();
  }
}
```

A couple issues though is that, as you can see on the 2nd line I knew which element was scrollable and where to find it. Also it carries scroll inertia over so if you scroll outside the modal quickly/strongly and then move the mouse into the modal, scroll events will still be firing and cause the modal to scroll.

For touchmove events to figure out the `delta` of a touch scroll you'd listen to a `touchstart` event and then do the calculation during subsequent `touchmove` events.

So it starts to get pretty complex so I'm going to just set a class on html, body like we said.
+@robrichard

**Comment by PeteJodo** [comment]
P.S. currentTarget did not work actually. It stopped ALL scrolling including in the modal

**Comment by PeteJodo** [comment]
Using inline styling `overflow: hidden`. Setting it inline does not cause the "jump to top of screen" issue that occurs when setting it as a class.

Closing
